### PR TITLE
Exposed closing full screen video player method from WKWebView

### PR DESCRIPTION
**Pull request by julianjohn**
Firstly, Thank you for this library. 😄

I have a use case where I would like to exit the video from fullscreen programmatically. I researched and found a possible solution. Please take a look.

Note: I am new to the latest Swift features, and every improvement suggestion is welcomed.

### CODE REVIEW

**Comment by SvenTiigi** [comment]
Hi @julianjohn,

Thanks for your PR 👍 
An option to invoke the `closeAllMediaPresentations` API of the WKWebView is a great addition to the YouTubePlayerKit.

After resolving the pending merge conflicts the PR should be good to.

**Comment by julianjohn** [comment]
@SvenTiigi I think I have fixed the issue. Please check.

**Comment by SvenTiigi** [comment]
Hi @julianjohn,

Your PR still has a merge conflict with the develop branch. 
After those conflicts have been resolved the PR should be ready to merge.

**Comment by julianjohn** [comment]
Resolved for sure this time 😅

**Comment by julianjohn** [comment]
Do you have any timeline for the next release?

**Pull request merged**
